### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by vibsdrockstar** [vibsdrockstar/pong#1]
![up](https://cloud.githubusercontent.com/assets/18600300/15997528/dda638aa-3152-11e6-952f-d166cb6c617a.png)
![screenshot2](https://cloud.githubusercontent.com/assets/18600300/15997530/eb1dad10-3152-11e6-9310-24b5f60709ae.png)
![s4](https://cloud.githubusercontent.com/assets/18600300/15997534/f6fa1588-3152-11e6-9b84-846dbcd2a803.png)
![s3](https://cloud.githubusercontent.com/assets/18600300/15997541/020f4ec0-3153-11e6-9680-1b713b797268.png)

**Comment by vibhcool** [comment]
Does your game work? I doubt that. It is giving nullpointer exception
